// src/data/dummyData.js
export const genres = [
    '판타지',
    '액션',
    '로맨스',
    '드라마',
    '무협/사극',
    '코미디',
    '스릴러',
    'SF',
    '스포츠',
    '일상',
  ];
  
  export const dummyProducts = [
    {
      id: 1,
      title: '판타지 웹툰 시즌1',
      category: '웹툰',
      genre: '판타지',
      price: 12000,
      status: 'sell',
      image: '/api/placeholder/300/300',
    },
    {
      id: 2,
      title: '액션 히어로 웹툰',
      category: '웹툰',
      genre: '액션',
      price: 15000,
      status: 'sell',
      image: '/api/placeholder/300/301',
    },
    {
      id: 3,
      title: '로맨스 웹툰 굿즈',
      category: '굿즈',
      genre: '로맨스',
      price: 25000,
      status: 'sell',
      image: '/api/placeholder/300/302',
    },
    {
      id: 4,
      title: '드라마 웹툰 포스터',
      category: '굿즈',
      genre: '드라마',
      price: 8000,
      status: 'notsell',
      image: '/api/placeholder/300/303',
    },
    {
      id: 5,
      title: '무협 웹툰 피규어',
      category: '굿즈',
      genre: '무협/사극',
      price: 35000,
      status: 'sell',
      image: '/api/placeholder/300/304',
    },
    {
      id: 6,
      title: '코미디 캐릭터 인형',
      category: '굿즈',
      genre: '코미디',
      price: 28000,
      status: 'sell',
      image: '/api/placeholder/300/305',
    },
    {
      id: 7,
      title: '스릴러 웹툰 시즌2',
      category: '웹툰',
      genre: '스릴러',
      price: 14000,
      status: 'sell',
      image: '/api/placeholder/300/306',
    },
    {
      id: 8,
      title: 'SF 우주전쟁 웹툰',
      category: '웹툰',
      genre: 'SF',
      price: 16000,
      status: 'sell',
      image: '/api/placeholder/300/307',
    },
    {
      id: 9,
      title: '스포츠 웹툰 컬렉션',
      category: '웹툰',
      genre: '스포츠',
      price: 22000,
      status: 'notsell',
      image: '/api/placeholder/300/308',
    },
    {
      id: 10,
      title: '일상 웹툰 팬아트',
      category: '팬아트',
      genre: '일상',
      price: 18000,
      status: 'sell',
      image: '/api/placeholder/300/309',
    },
    {
      id: 11,
      title: '판타지 캐릭터 스티커',
      category: '굿즈',
      genre: '판타지',
      price: 5000,
      status: 'sell',
      image: '/api/placeholder/300/310',
    },
    {
      id: 12,
      title: '액션 웹툰 팬아트',
      category: '팬아트',
      genre: '액션',
      price: 17000,
      status: 'sell',
      image: '/api/placeholder/300/311',
    },
    {
      id: 13,
      title: '로맨스 웹툰 시즌3',
      category: '웹툰',
      genre: '로맨스',
      price: 13000,
      status: 'sell',
      image: '/api/placeholder/300/312',
    },
    {
      id: 14,
      title: '드라마 웹툰 팬아트 컬렉션',
      category: '팬아트',
      genre: '드라마',
      price: 20000,
      status: 'notsell',
      image: '/api/placeholder/300/313',
    },
    {
      id: 15,
      title: '무협 웹툰 시리즈',
      category: '웹툰',
      genre: '무협/사극',
      price: 15000,
      status: 'sell',
      image: '/api/placeholder/300/314',
    },
    {
      id: 16,
      title: '코미디 웹툰 굿즈 세트',
      category: '굿즈',
      genre: '코미디',
      price: 32000,
      status: 'sell',
      image: '/api/placeholder/300/315',
    },
    {
      id: 17,
      title: '스릴러 캐릭터 피규어',
      category: '굿즈',
      genre: '스릴러',
      price: 40000,
      status: 'sell',
      image: '/api/placeholder/300/316',
    },
    {
      id: 18,
      title: 'SF 웹툰 포스터',
      category: '굿즈',
      genre: 'SF',
      price: 9000,
      status: 'notsell',
      image: '/api/placeholder/300/317',
    },
    {
      id: 19,
      title: '스포츠 캐릭터 티셔츠',
      category: '굿즈',
      genre: '스포츠',
      price: 23000,
      status: 'sell',
      image: '/api/placeholder/300/318',
    },
    {
      id: 20,
      title: '일상 웹툰 시즌1',
      category: '웹툰',
      genre: '일상',
      price: 11000,
      status: 'sell',
      image: '/api/placeholder/300/319',
    },
  ];